### ISSUE TITLE
Including some of the Where statement

### ISSUE THREAD

**Issue by avanderhoorn** [opbeat/sql-summary#2]
Just wondering if you had considered having an option that allows you to include part of the `where` clause? Not exactly sure how it would work but off the top of my head, you would be able to say include all or x number of characters.

**Comment by watson** [comment]
The `WHERE` clause can be really long and complicated though. Do you have a specific use-case in mind?

**Comment by avanderhoorn** [comment]
Agreed... I would imagine that you would specify how many characters of the `where` clause you want.

**Comment by watson** [comment]
@avanderhoorn what is your use-case?

**Comment by alvarolobato** [comment]
We won't do this task in the short term, if your really feel this task is needed, please reopen it and let us know.
